name = "COOP S6"
author = "Pablo/Temmpou"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5110826112ebe3fa6920f4c459b5ab70362b3631c023f75a101af635bb4b5f7f"

[versions]
forge = "47.2.14"
minecraft = "1.20.1"
