name = "COOP S6"
author = "Pablo/Temmpou"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00330779ac371035ad0cc075d1a42d7a0da90fe59de15ed2978a4d2a523044f8"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
