name = "COOP S6"
author = "Pablo/Temmpou"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "592ad1a7d5d03a426ef04bb8fdd9ac7f274f1162f9e60a4ee3dfad692b21e0be"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
