name = "COOP S6"
author = "Pablo/Temmpou"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10dfcc7f27b5bc94f2c755a6b32f8961f3c515ea7b30480128960011bd4a30f6"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
